About
Viking3045/IceCream pull request #36
Opened 2022-12-25 15:56 UTC by OlenaMrn

2022-12-25 17:18 UTC, Viking3045 requested changes

2022-12-25 17:18 UTC, Viking3045 commented on src/partials/about.html
> +  <div class="about-container container">
Може цей клас прописати як about__container

2022-12-25 17:18 UTC, Viking3045 commented on src/partials/about.html
> +  <div class="about-container container">
в інших класах знизу так само

2022-12-25 17:18 UTC, Viking3045 commented on src/sass/layout/_about.scss
> +.about__text {
Потрібно прописати через амперсант &__text і вставити до селектору .about

2022-12-25 17:18 UTC, Viking3045 commented on src/sass/layout/_about.scss
> +.about {
повторюється клас, потрібно те що в середині перенести до класу який вже прописаний вище

2022-12-25 17:18 UTC, Viking3045 commented on src/sass/layout/_about.scss
> +.image-box::before {
Потрібно прописати через амперсант і вставити в селектор image-box

2022-12-25 17:18 UTC, Viking3045 commented on src/sass/layout/_about.scss
> +.about__button {
Потрібно прописати через амперсант і вставити в селектор about

2022-12-25 19:53 UTC, OlenaMrn commented
Виправила класи

2022-12-26 11:25 UTC, Viking3045 requested changes

2022-12-26 11:25 UTC, Viking3045 commented on src/partials/about.html
> +          <svg class="button-icon" width="12" height="12">
мабуть цей клас краще записати як about__icon

2022-12-26 11:25 UTC, Viking3045 commented on src/sass/layout/_about.scss
> +    &:focus svg {
мабуть краще переписати цей селектор через селектор класу, а не селектор тегу, якщо внести зміни що записав вище то цьому значенню відповідає селектор about__icon

2022-12-26 11:25 UTC, Viking3045 commented on src/sass/layout/_about.scss
> +.button-icon {
Якщо внести зміни які прописав раніше то цей селектор буде називатись &__icon і повинен бути переміщений в селектор .about

2022-12-26 12:34 UTC, Viking3045 requested changes

2022-12-26 12:34 UTC, Viking3045 commented on src/sass/layout/_about.scss
> +      .about__icon {
данні цього селектора потрібно перемістити в селектор який знаходиться в 143 рядку під назвою &__icon

2022-12-26 15:46 UTC, Viking3045 approved these changes

2022-12-26 15:46 UTC, Viking3045 commented on src/sass/layout/_about.scss
> +      .about__icon {
Цей селектор також потрібно винести під амперсант, &__icon та перемістити в селектор .about

2022-12-26 15:47 UTC, Viking3045 approved these changes

2022-12-26 15:47 UTC, merged